### ISSUE TITLE
Searches no longer return anything

### ISSUE THREAD

**Issue by kevslinger** [haw230/a-search-of-hogwarts#4]
Hi!

Let me start off by saying I love this project. Having a centralized search engine for the texts has come in handy quite often! I appreciate the work you put in to make this website possible.

Recently, I've noticed the site not working for me. When I search (even simple things such as "Harry Potter" or "Hermione"), I get either an "Error for Occurrences" or empty curly braces returned. I've heard other people are getting the same error. Is this an issue you're aware of?

Again, thanks for creating such a useful project! I think it's so cool to see the coding and Harry Potter communities intertwine.

(Steps to reproduce: 
  1.) Go to potter-search.com
  2.) Enter text into the text box.
  3.) Ensure all books are checked (e.g. click "check all")
  4.) Click the magnifying glass to search
  5.) Observe empty curly braces or "Error for Occurrences" returned
)

**Comment by haw230** [comment]
Hey Kevin, thank you for your kind words! Unfortunately this is because my trial on Google Cloud Platform has ended which is why the response returns an error. The frontend is still being hosted because my AWS trial lasts longer. I will see what I can do for hosting. Thanks for bringing this to my attention, and I'm glad you found the tool useful.

**Comment by haw230** [comment]
Hi again @kevslinger, this issue should be fixed now. Thanks for bringing this to my attention (I did not think anyone was still using this tool). Please let me know if it works!

**Comment by kevslinger** [comment]
Hi @haw230, thank you so much! It works perfectly now :)
